site_name: Text Mood Processor Documentation

nav:
  - Home: index.md
  - API Gateway:
      - Overview: api_gateway/overview.md
      - Endpoints: api_gateway/endpoints.md
      - Files: api_gateway/files.md
  - Change Tone Service:
      - Overview: change_tone_service/overview.md
      - Endpoints: change_tone_service/endpoints.md
      - Files: change_tone_service/files.md
  - Tone Analyzer Service:
      - Overview: tone_analyzer_service/overview.md
      - Endpoints: tone_analyzer_service/endpoints.md
      - Files: tone_analyzer_service/files.md
  - Model Inference Service:
      - Overview: model_inference_service/overview.md
      - Endpoints: model_inference_service/endpoints.md
      - Files: model_inference_service/files.md

theme:
  name: material
